### ISSUE TITLE
별찍기 시각화

### ISSUE THREAD

**Issue by ujkkk** [on-Haeya/pre-python-viz#4]
## 📝 Description
**무엇을?**
- 별찍기 코드 시각화하기

**왜?**
- 기술 검증

## ❗️Todo
- [x] 백엔드에서 프론트로 넘겨줘야할 데이터 분석
- [x] 코드 해석 후 데이터 추출
- [x] 웹사이트 띄우기
- [x] 모나코 에디터 
- [ ] 시각화

## ETC
기타사항

**Comment by SongGwanSeok** [comment]
별찍기 json 구조

```json{
  "steps": [
    {
      "type": "Assign",
      "id": "a",
      "value": 3
    },
    {
      "type": "For",
      "exprs": [
        {
          "for_var": [
            {
              "type": "Assign",
              "id": "i",
              "value": 0
            },
            {
              "type": "Assign",
              "id": "start",
              "value": 0
            },
            {
              "type": "Assign",
              "id": "end",
              "value": 2
            }
          ],
          "body": [
            {
              "type": "func",
              "name": "print",
              "value": [
                "'*' * (i+1)",
                "'*' * 1",
                "'*'"
              ]
            }
          ]
        },
        {
          "for_var": [
            {
              "type": "Assign",
              "id": "i",
              "value": 1
            }
          ],
          "body": [
            {
              "type": "func",
              "name": "print",
              "value": [
                "'*' * (i+1)",
                "'*' * 2",
                "'**'"
              ]
            }
          ]
        },
        {
          "for_var": [
            {
              "type": "Assign",
              "id": "i",
              "value": 2
            }
          ],
          "body": [
            {
              "type": "func",
              "name": "print",
              "value": [
                "'*' * (i+1)",
                "'*' * 3",
                "'***'"
              ]
            }
          ]
        }
      ]
    }
  ]
}```

**Comment by SongGwanSeok** [comment]
좀 더 세부적인 목표로 이슈 생성 합시다

**Comment by ujkkk** [comment]
` 
  @dataclass
  class Target:
      id: str
      type: str
  
  @dataclass
  class Value:
      exp: str
      eval: str

 # AST 노드를 순회하면서 실행
    for node in parsed_ast.body:
        # 변수 선언 및 할당 처리
        if isinstance(node, ast.Assign):
            for target in node.targets:
                eval_value = eval(compile(ast.Expression(node.value), '', 'eval'), global_vars, local_vars)
                # 표현식 추출
                expression = ast.unparse(node.value) if hasattr(ast, 'unparse') else compile(ast.Expression(node.value),
                                                                                             '', 'eval').co_code
                target_obj = Target(id=target.id, type=get_type_string(eval_value))
                value_obj = Value(exp=expression, eval=eval_value)

                # json 형식 생성
                json_output = create_json(target_obj, value_obj)
                print(json_output)`
